# fly.toml app configuration file generated for app-little-waterfall-5778 on 2025-03-09T23:36:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-little-waterfall-5778'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 7777
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
